### ISSUE TITLE
grSim not compilling with new version of vartypes

### ISSUE THREAD

**Issue by hbritto** [mani-monaj/grSim#17]
Vartypes was recently updated to version 0.8 and it breaks the compilation of grSim.

The problem is they have defined a **VarPtr** type, which is a typedef from *std::tr1::shared_ptr<VarTypes::VarType>*. As this project uses the *std::shared_ptr<VarTypes::VarType>*, this breaks compilation.

The solution I've found is to manually change in configwidget.cpp and .h the 'shared_ptr' for **std::tr1::shared_ptr**, this made it compile correctly again.

I'd like to know if this is a fine change or if it breaks something during runtime.

**Comment by mani-monaj** [comment]
This is fixed in #19
