### ISSUE TITLE
Text files update

### ISSUE THREAD

**Issue by mani-monaj** [mani-monaj/grSim#3]
Read the wiki page I created regarding standards, then
1. Please move all information regarding changes to CHANGELOG, authors to AUTHORS and installation to INSTALL from README
2. Update the CHANGELOG based on standards stated in wiki.
3. Update AUTHORS file based on standards stated in wiki.
4. Update INSTALL file based on standards stated in wiki.

**Comment by mahi97** [comment]
can we close this issue too ? or is there something that needed to be done.

**Comment by mani-monaj** [comment]
@mahi97 You are right. It can be closed.
