### ISSUE TITLE
grsim.xml ?

### ISSUE THREAD

**Issue by samedcildir** [mani-monaj/grSim#34]
There is `world=VarXML::read(world,(QDir::homePath() + QString("/.grsim.xml")).toStdString());` line in configwidget.cpp line 130.

Because of that line, BallMass becomes 0 and the program gives `ODE INTERNAL ERROR 1: assertion "dMassCheck(mass)" failed in dBodySetMass()` error.

What is grsim.xml? and is that line really necessary?

**Comment by mahi97** [comment]
I don't get this error on my machine ... .
Can you give me the specific of your PC and the way you build grSim and dependencies ?

**Comment by mahi97** [comment]
The grsim.xml save the values of Vartypes widget that contain the parameters of geometry, physics and communication.

It used to save data that someone configured for grSim and load it on the next time that grSim is running.

If ballMass becomes 0 it's probably because in grSim.xml file 0 is saved for ballMass,
I think you can change it manually or delete the grsim.xml and let grsim make another one with default values.

**Comment by samedcildir** [comment]
I'm using Ubuntu 14.04, I followed the instructions on the GitHub for build.

grsim.xml file looks ok. Ball mass is set to 0.043 but for some reason VarXML::read cannot read it

**Comment by mahi97** [comment]
Can you check and make sure that ode is installed in `double-precision` mode or not ?

**Comment by samedcildir** [comment]
I found the error. When it writes the doubles it writes with dot(.) such as `0.043`. But for some reason it requires comma(,) when its reading such as `0,043`.

**Comment by mahi97** [comment]
Interesting i don't have this problem on mine!
Do you use English for your regions and language too ?

**Comment by mani-monaj** [comment]
@samedcildir It's most likely a `locale` problem. I think your system's `locale` uses `,` as the decimal separation character. The easiest (but not the most convenient) is to set your `locale` to `en_US.utf8` or similar. The long term solution would to fix this issue in *VarTypes* (needs confirmation though).

**Comment by samedcildir** [comment]
Sorry I forgot to respond. My systems language is English but probably my locale is `tr_TR` so I guess if I change my locale the problem will be solved.
